tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "bibendi/dip"

brew "gnupg"
brew "pinentry-mac"
brew "dip"

cask "1password"
cask "1password-cli"
cask "visual-studio-code"
cask "tableplus"