tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

brew "gnupg"
brew "pinentry-mac"
cask "1password"
cask "1password-cli"
cask "visual-studio-code"