#!/bin/bash
set -e

if ! [ -L ~/.gnupg ] || ! [ -L ~/.ssh ]
then
  echo "Run script/setup first!" >&2
  exit 1
fi

onepassword_login() {
  if ! command -v op >/dev/null
  then
    echo "Install op first!" >&2
    exit 1
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_MY" ]
  then
    echo "Logging into 1Password..."
    eval $(op signin my)
  fi
}

onepassword_get() {
  if [ -f "$HOME/$2" ]
  then
    echo "$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op get document "$1" > "$HOME/$2"
  chmod 600 "$HOME/$2"
}

onepassword_get gdsxak2evvfvlju3b26oadajjq .ssh/id_rsa
onepassword_get tw64ybvsabhrbarnotcoelg5kq .gnupg/info@peterberkenbosch.nl_private.gpg

echo "Storing SSH keys in keychain..."
ssh-add -K

echo "Setting up GPG..."
if ! command -v gpg >/dev/null
then
    echo "Install GPG first!" >&2
    exit 1
fi

chmod 700 ~/.gnupg
gpg --import ~/.gnupg/info@peterberkenbosch.nl_pub.gpg \
             ~/.gnupg/info@peterberkenbosch.nl_private.gpg
gpg --import ~/.gnupg/0x26CA21CD9509247E.pub.asc