#!/bin/sh
# Run by Strap after installing Brewfile dependencies

cd $(dirname $0)/..

script/install-vs-code-extensions

if [ "$SHELL" != "/bin/zsh" ]
then
  chsh -s /bin/zsh peterberkenbosch
fi

# Install globally used gems
gem install dip
gem install solargraph
